### ISSUE TITLE
Add Citation to the README.

### ISSUE THREAD

**Issue by HeloiseS** [1313e/PRISM#5]
I know it's just come out on ArXiv (looking forward to giving it a go), but it can be easy to forget to update the README ;) 

Add a link to your [ArXiv paper](https://arxiv.org/abs/1901.08725), and the bibtex where you had 
"Put reference to *PRISM* paper here!"

```
@ARTICLE{2019arXiv190108725V,
   author = {{van der Velden}, E. and {Duffy}, A.~R. and {Croton}, D. and 
	{Mutch}, S.~J. and {Sinha}, M.},
    title = "{Model dispersion with PRISM; an alternative to MCMC for rapid analysis of models}",
  journal = {arXiv e-prints},
archivePrefix = "arXiv",
   eprint = {1901.08725},
 primaryClass = "astro-ph.IM",
 keywords = {Astrophysics - Instrumentation and Methods for Astrophysics, Physics - Computational Physics},
     year = 2019,
    month = jan,
   adsurl = {http://adsabs.harvard.edu/abs/2019arXiv190108725V},
  adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}
```

**Comment by 1313e** [comment]
Haha.
I was actually refreshing ADS almost every hour to check if the paper had already been indexed or not.
Apparently, the new ADS system does not have it yet, but the old one does.
So, yeah, I can add the paper reference to the README and the docs now.
Thanks for the reminder!

**Comment by HeloiseS** [comment]
... or use the old ADS when looking for new publications ;) it's always in there before the new ADS! :D
