### ISSUE TITLE
README example hangs on projection creation.

### ISSUE THREAD

**Issue by fonnesbeck** [1313e/PRISM#7]
I've installed PRISM on both a Debian Linux system and a macOS machine successfully, however executing the example shown in the README file does not run to completion. Specifically, it hangs at the projection creation step with 0% completed. 

Here is a screen shot of what I am seeing:

![image](https://user-images.githubusercontent.com/81476/52885686-a99b4b80-3137-11e9-819b-028ea4339b3e.png)

I assume the example is meant to run quickly, given how small it is.

In both cases PRISM was installed in a conda virtualenv with Python 3.7.2, using pip on the cloned master branch.

**Comment by 1313e** [comment]
@fonnesbeck Thanks for your report.
I just tried this on a Windows machine using Python 3.7.2 and simply installing PRISM from the master branch.
The projections are created for me with no problem.

However, for the 2D projections, it tries to create a large Latin-Hypercube that satisfies a bunch of criteria (as is done by default in PRISM) and this causes it take a very long time to create one.
Guess it is finally time to relax that condition a bit.

I just changed the default value of the associated parameter on all branches.
Can you try to run the example again?

**Comment by fonnesbeck** [comment]
OK, it appears to run now (about 120s/hypercube) on my MacBook Pro. Thanks.
