### ISSUE TITLE
getProject getShot command à la shotgun

### ISSUE THREAD

**Issue by plboily** [1313e/PRISM#9]
Hi, i am currently evaluating prism on the API side. Im looking everywhere and i dont see any "wrapper" command doing something like, getProjects() and getShots(project) or something like this.

Im a shotgun api user (sadly) and is way to get shots, assets, and versions is very nice. Do you have something equivalent?

Thanks a lot

**Comment by 1313e** [comment]
@plboily I am really sorry, but I have absolutely no idea what you mean.
Could you explain your enquiry in a bit more detail?

**Comment by plboily** [comment]
Hi,
   What I'm looking for is an API command to access basic element inside
prism. So I want command to answer these questions:

1) Give me all the shots for this project ('proj1')
2) Give me all the version available for this specific shot (s001_00001)

I know I can use the UI to access the shots, but I'm wondering if you have
simple python command to question prism about it?

Is it more clear now?

**Comment by 1313e** [comment]
@plboily Thanks for your response.
I'm currently having a bit of trouble understanding what you mean with "shot". 
Could you maybe give me a concrete example, such that we understand each other?

**Comment by plboily** [comment]
Im on the wrong Prism git-hub:

https://github.com/RichardFrangenberg/Prism

Sorry for that!!

**Comment by 1313e** [comment]
@plboily Aha, that clears that up.
No problem, just glad we figured that out.
